### ISSUE TITLE
Enable Matemat-Stats

### ISSUE THREAD

**Issue by tensau** [shackspace/kiosk_v4#4]
API-URL und Produktbezeichnung sind gefixt, und das Live-Tracking tut nun auch wieder :)
--> bitte bei Gelegenheit auf dem Kiosk wieder aktivieren

**Comment by uescher** [comment]
Fixed with
https://github.com/shackspace/kiosk_v4/commit/ca695799628dbbad15eeb2f1b78a72a2b4006485

**Comment by recnac** [comment]
Bist du sicher, dass das funktioniert? Habe 4 Buttons nie getestet.

**Comment by tensau** [comment]
Jup, funktioniert :)
